Added list of all compilable languages in --help
BuilderIO/mitosis pull request #1102
Opened 2023-04-07 19:43 UTC by SupaSibs

I added some entries to the old --to / -t, as it was uncomplete. I also changed the list of --to and --from into alphabetical order because it's super annoying otherwise.

2023-04-08 17:01 UTC, tomByrer commented
Should `Sveltosis` be listed in --from, or is that too alpha?

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&inputTab=M4NwpgNgLmQ%3D&code=DwZwxgTglgDgLgPgFAAIUBsCmcUDsCGAtpigLwoDkAynJgG6YUDcSwA9ONPMqwCZR1kaYFFwwArjgBGo3gC46%2BdOMykA3gWIBfFGyEoAEpnToA9gEIUASRRh8uFBHEPRKAEqZ8YOABoUANRU%2FKlN0KF4%2FUwgUABkoAEdxcPNWNn5BIA%3D

2023-04-08 17:03 UTC, SupaSibs commented
It definitely should, but when I tried to type in -f sveltosis it didnt work idk why

2023-04-08 17:03 UTC, SupaSibs commented
It definitely should, but when I tried to type in -f sveltosis it didnt work idk why

2023-04-08 17:06 UTC, SupaSibs commented
Yeah, still not working. It's a shame though as I like svelte code more than the lite jsx code

2023-04-08 17:11 UTC, SupaSibs commented
It seems that Sveltosis isn't even an option in -f (i checked the commands folder for compile and build)

2023-04-08 21:08 UTC, tomByrer commented
> It seems that Sveltosis isn't even an option in -f (i checked the commands folder for compile and build)

Yes, I was suggesting for you to add it in ;)

I'm not sure how much help this will be, but here is the original sveltosis repo:
https://github.com/sveltosis/sveltosis/tree/main/examples/my-component-library

2023-04-10 13:48 UTC, SupaSibs commented
Oh, ok. I'll try and check the sveltosis parser in parsers folder and see if there's naything i can use.

2023-04-10 14:13 UTC, SupaSibs commented
I found out how to get the parser into the CLI, but what **is* the string_ argument in parseSvelte for? It only seems to be used in the mapAst function, but it's only used for one function. Should it be say the JSON, or the JSON parsed to the string, or a value?

2023-04-12 09:21 UTC, SupaSibs commented
Thanks, now I understood it. But I have a question, how do I build/test mitosis without NPM? I'm trying to test the new cli and core to see if they work but I don't know how...

2023-04-12 19:17 UTC, samijaber approved these changes

2023-04-12 19:18 UTC, samijaber commented
> Thanks, now I understood it. But I have a question, how do I build/test mitosis without NPM? I'm trying to test the new cli and core to see if they work but I don't know how...

You can test by running the `mitosis` command inside any of the example folders within the monorepo. For example: https://github.com/BuilderIO/mitosis/blob/26a4f4ffdaef0f0001038ed5adbb7f0669a832e8/examples/todo/package.json#L4

You can run `npm exec mitosis compile -f` in this sub-folder, and it should work correctly.

2023-04-12 19:19 UTC, samijaber requested changes

2023-04-12 19:19 UTC, samijaber commented on packages/core/src/parsers/svelte/index.ts
> +export {parseSvelte, mapAstToMitosisJson}
I think this line is incorrect and causing build failures. You are already exporting `parseSvelte`. You just need to add `export` behind the `mapAstToMitosisJson` declaration

2023-04-13 17:39 UTC, SupaSibs commented on packages/core/src/parsers/svelte/index.ts
> +export {parseSvelte, mapAstToMitosisJson}
Damn that totally went over my head. I'm going to make a new PR for this as the topic has gone from "fixing -t in CLI" to "adding Sveltosis to cli", so i'll have to close this one.

2023-04-13 17:39 UTC, SupaSibs commented
Closed this PR as the topic has changed from fixing -t to adding sveltosis to cli.

2023-04-13 17:39 UTC, closed without merging