feat: add config definedComponent for vue3 optionsApi
BuilderIO/mitosis pull request #1104
Opened 2023-04-09 03:41 UTC by kingzez

## Description

Add a short description of:
-  https://github.com/BuilderIO/mitosis/issues/1103

2023-04-09 08:47 UTC, kingzez commented
I run `yarn ci` is success.

2023-04-11 19:52 UTC, samijaber commented
`definedComponent` seems like a great default to have. I would add a `true` default for it here:

https://github.com/BuilderIO/mitosis/blob/26a4f4ffdaef0f0001038ed5adbb7f0669a832e8/packages/core/src/generators/vue/vue.ts#L98-L103

and update snapshots

2023-04-13 14:22 UTC, kingzez commented
@samijaber All done.

2023-04-13 14:40 UTC, samijaber requested changes

2023-04-18 16:56 UTC, kingzez commented on packages/core/src/generators/vue/optionsApi.ts
> +  const isDefineComponent = options.vueVersion >= 3 && options.defineComponent;
Sorry, I ignore this notification.

I suggest  not to remove the vueVersion checks for the time being, there are still a large number of vue application versions lower than 2.7, it is recommended to keep it for a while.

2023-04-18 17:16 UTC, samijaber commented on packages/core/src/generators/vue/optionsApi.ts
> +  const isDefineComponent = options.vueVersion >= 3 && options.defineComponent;
Mitosis already generates a lot of code for `vue2` that only works for 2.7+. So we already are not compatible with Vue <2.7.

Vue 2.6 was released on February 4, 2019, and Vue 2.7 on July 1, 2022. Also, Vue 2 will reach end of life December 2023: https://v2.vuejs.org/v2/guide/migration-vue-2-7.html#Implications-of-the-2-7-Release

Since End of Life is coming fairly soon, and upgrading to 2.7 is only a minor version upgrade without any breaking changes, I don't really want Mitosis development to be slowed down by supporting Vue 2.6 or lower.

2023-04-18 17:36 UTC, kingzez commented on packages/core/src/generators/vue/optionsApi.ts
> +  const isDefineComponent = options.vueVersion >= 3 && options.defineComponent;
I thought about it, what you said also makes sense. I will remove the `vueVersion` checks.

2023-04-18 19:39 UTC, samijaber approved these changes

2023-04-18 19:39 UTC, merged