fix 1319 about the solid remove a property
BuilderIO/mitosis pull request #1369
Opened 2024-02-20 08:08 UTC by JerryWu1234

## Description

fix #1319 

Add a short description of:
- what changes you made, 
- why you made them, and 
- any other context that you think might be helpful for someone to better understand what is contained in this pull request. 

This sort of information is useful for people reviewing the code, as well as anyone from the future trying to understand why changes were made or why a bug started happening.

2024-03-29 01:08 UTC, JerryWu1234 commented
@samijaber  please review

2024-04-04 14:41 UTC, samijaber requested changes

2024-04-04 14:41 UTC, samijaber commented on packages/core/src/generators/solid/blocks.ts
> -  for: 'htmlFor',
instead of removing the `ATTRIBUTE_MAPPERS` object completely, can you only remove this one key/value pair? That way the infrastructure will still exist for the future

2024-07-31 19:04 UTC, samijaber commented on .changeset/flat-kangaroos-tan.md
> +fix 1319 about the solid remove a property
```suggestion
Solid: stop mapping `for` to `htmlFor`
```

2024-07-31 19:04 UTC, merged