Support for custom generators / targets
BuilderIO/mitosis pull request #1370
Opened 2024-02-21 08:58 UTC by JerryWu1234

## Description

#1322

Add a short description of:
- Support for custom generators / targets
- #1322

This sort of information is useful for people reviewing the code, as well as anyone from the future trying to understand why changes were made or why a bug started happening.

2024-02-21 21:27 UTC, samijaber commented on packages/cli/src/build/build.ts
> -      generator: getGeneratorForTarget({ target }) as any,
This is the default behaviour, we still want it. Otherwise every user has to provide every generator every time.

```ts
generator: options.generators[target] || getGeneratorForTarget({ target })
```

2024-02-21 21:27 UTC, samijaber requested changes
Need to preserve default behaviour

2024-02-22 03:25 UTC, JerryWu1234 commented on packages/cli/src/build/build.ts
> -      generator: getGeneratorForTarget({ target }) as any,
I set a default behavior in `packages/cli/src/build/build.ts`
my way [`generators: Object.assign(targets, config?.generators)`](https://github.com/BuilderIO/mitosis/blob/71511a8668f46a3058b8f725abb0943bc49f1d61/packages/cli/src/build/build.ts#L57)

2024-02-23 05:16 UTC, JerryWu1234 commented on packages/cli/src/build/build.ts
> -      generator: getGeneratorForTarget({ target }) as any,
@samijaber I just want to confirm if we still have to tweak?

2024-02-26 03:25 UTC, JerryWu1234 commented
> Need to preserve default behaviour

@samijaber please check

2024-05-08 18:58 UTC, samijaber commented on packages/core/src/types/config.ts
> +   */
```suggestion
```

2024-05-08 18:59 UTC, merged

2024-05-08 19:48 UTC, samijaber commented
Thanks for putting this together @JerryWu1234 ! Thank you for your patience in getting it merged as well.