Add support for basic components in React native
BuilderIO/mitosis pull request #1475
Opened 2024-06-08 11:13 UTC by Othman2001

## Description

Please provide the following information:

- What changes have you made:
Support button, touchable opacity, Image  and Linking
- Why you made them, and:
I think this change is very important to react native generator as it is currently is not supporting all core components.
- Any other useful context:
I think using a Button is much more convenient than pressable, that's why I migrated pressable usage to the button. 
the fiddle is not working properly with the Image component for some reason, but I managed to run the source code locally and tested all of my changes.
Make sure to follow the PR preparation steps in [CONTRIBUTING.md](../CONTRIBUTING.md#preparing-your-pr) before submitting your PR:

- [x] Format the codebase
- [x] Update all snapshots

2024-06-10 19:26 UTC, samijaber requested changes

2024-06-10 19:26 UTC, samijaber commented on packages/core/src/generators/react/blocks.ts
> +      .map((item) => blockToReact(item, options, component, needsToRenderSlots))
This code is crashing due to `needsToRenderSlots` being created after this line:


https://github.com/BuilderIO/mitosis/blob/215c3783cb2e22dbbf8912a6e6129640f87e119b/packages/core/src/generators/react/blocks.ts#L287

You need to move the initialization to the start of `blockToReact`

2024-06-14 08:28 UTC, Othman2001 commented on packages/core/src/generators/react/blocks.ts
> +      .map((item) => blockToReact(item, options, component, needsToRenderSlots))
oh, makes sense i will fix this today 🙏

2024-06-15 09:39 UTC, Othman2001 commented on packages/core/src/generators/react/blocks.ts
> +      .map((item) => blockToReact(item, options, component, needsToRenderSlots))
Done ✅

2024-06-17 13:56 UTC, samijaber commented on packages/core/src/generators/react-native/index.ts
> -              node.name = 'Pressable';
I just realized: we still want this condition in our logic. If an element has `onClick` but is not `a` or `button`, we need it to be `Pressable`. 

With your changes, it will become a `View` which cannot be pressed. This breaks `onClick` handling.

2024-06-17 14:16 UTC, samijaber requested changes
Uncovered a few other issues with how the components are being generated.

2024-06-17 14:16 UTC, samijaber commented on packages/core/src/generators/react/blocks.ts
> +      source = `require('${json.properties.src}')`;
What situation is this meant for exactly? generating `require` statements in our components does not seem like something we want to do in the general case.

2024-06-17 14:16 UTC, samijaber commented on packages/core/src/generators/react/blocks.ts
> +      source = `require('${json.properties.src}')`;
I think the generator should only do `{ uri: '${THE_SRC}' }`

2024-06-17 14:16 UTC, samijaber commented on packages/core/src/generators/react/blocks.ts
> +  }
These code blocks have two issues:

- they are wiping out all props for `TouchableOpacity` and `Image`. See my comment in the snapshot.
- they only handle `json.properties.*`, not `json.bindings.*`. Properties are static, bindings are dynamic JS code blocks (`<img src="foo" />` vs `<img src={props.foo} />`). You need to handle both in the generator.

What you want to do instead is handle `src`, `href` and `onClick` in the for loops below which iterate over `json.bindings` and `json.properties`: https://github.com/BuilderIO/mitosis/blob/f6e6d95f06963a15902ad1eb9899918c1f8e3da6/packages/core/src/generators/react/blocks.ts#L202-L275

Let me know if you need any additional guidance around how to do that.

2024-06-17 16:47 UTC, Othman2001 commented on packages/core/src/generators/react-native/index.ts
> -              node.name = 'Pressable';
yeah sorry i missed this

2024-06-17 16:49 UTC, Othman2001 commented on packages/core/src/generators/react/blocks.ts
> +      source = `require('${json.properties.src}')`;
if image is local, it should be imported using require, if it is URI it should be` {uri:"url of image"}`

2024-06-17 16:51 UTC, Othman2001 commented on packages/core/src/generators/react/blocks.ts
> +  }
i see, i will be working on this comments and let you know if i needed any help, Thank you a lot for your help.

2024-06-17 17:11 UTC, Othman2001 commented on packages/core/src/generators/react/blocks.ts
> +      source = `require('${json.properties.src}')`;
i think this is because of the nature of Image component in RN, if you are using local images, you generally need to use the require function instead of using a URI string directly. This is because local images are bundled with the app and require is used to resolve the image source at build time.

2024-06-17 17:19 UTC, samijaber commented on packages/core/src/generators/react/blocks.ts
> +      source = `require('${json.properties.src}')`;
I see. in the case of `json.bindings.src`, you will need  to use `uri:` for all cases because bindings are dynamic and cannot be parsed at compile-time.

2024-06-21 13:04 UTC, Othman2001 commented on packages/core/src/generators/react/blocks.ts
> +  }
Hi @samijaber 
```
regarding the issue related to handling bindings and properties i think i managed to handle it by doing smth like this
    if (options.type === 'native' && json.name === 'Image') {
      let src;
      const imageSource = processBinding(String(json.bindings['src']?.code), options);
      if (json.properties.src) {
        const isUrl = json.properties.src
          ? /^(http|https):\/\/[^ "]+$/.test(json.properties.src)
          : false;
        let source;
        if (isUrl) {
          source = `{ uri: '${json.properties.src}' }`;
        } else {
          source = `require('${json.properties.src}')`;
        }
        return `<Image  source={${source}} />`;
      }
      if (imageSource) {
        src = `{ uri: ${imageSource} }`;
      }
      return `<Image source={${src}} />`;
    }
```
but regarding the issue of wiping out other props not sure what i need to do is there something like attributes for example where i can add all other props when i return Image like this, would appreciate help here plz 

`     return `<Image  source={${source}}  {...otherProps} />`;
`

2024-06-29 15:39 UTC, Othman2001 commented on packages/core/src/generators/react/blocks.ts
> +  }
@samijaber  I think this PR is ready for your review, Thank you.

2024-07-06 12:41 UTC, Othman2001 commented
> Uncovered a few other issues with how the components are being generated.

@samijaber  This PR is ready for you review now, I have resolved your comments, can you please check it whenever you are free 
Thank you

2024-07-09 21:51 UTC, samijaber commented on packages/core/src/generators/react/blocks.ts
> +    }
This has one issue: you are handling `json.bindings` and `json.properties` key/values in the same place. You need to handle them separately. This will require duplicating this logic.

What you need to do is:

- update this code block so that instead of referencing `json.properties.href`, `json.properties.src` etc. it is always _only_ referencing `json.bindings.*`.
- duplicate this block inside of the `for (const key in json.properties)` loop https://github.com/BuilderIO/mitosis/blob/f6e6d95f06963a15902ad1eb9899918c1f8e3da6/packages/core/src/generators/react/blocks.ts#L202-L220

and make sure that in this new case, it is only references `json.properties.*` key/values.

2024-07-17 10:46 UTC, Othman2001 commented on packages/core/src/generators/react/blocks.ts
> +    }
I see, I will work on this next week end hopefully 🙏  meanwhile I will move this pr to draft

2024-07-27 12:01 UTC, Othman2001 commented on packages/core/src/generators/react/blocks.ts
> +    }
@samijaber  Done, I have  moved  the logic to the two loops, for bindings and properties.
Sorry if were late resolving this.

2024-07-28 08:10 UTC, Othman2001 commented
@samijaber  I have resolved the comments now, and separated the logic on two loops like we agreed, sorry if i were late.

2024-07-30 18:41 UTC, samijaber approved these changes
Amazing job. Well done, and thank you for contributing this big improvement to the RN generator 🎉

2024-07-30 19:04 UTC, samijaber commented
@Othman2001 you need to re-run the snapshots one last time for it to fix a merge conflict, and you're good to go!

2024-07-31 18:39 UTC, Othman2001 commented
> @Othman2001 you need to re-run the snapshots one last time for it to fix a merge conflict, and you're good to go!

@samijaber  Done I have updated the snapshots, This PR is ready to go 🥳

2024-07-31 18:41 UTC, merged