feat: support destructuring of objects in Angular in HTML elements
BuilderIO/mitosis pull request #1522
Opened 2024-08-06 14:37 UTC by sidmohanty11

## Description

Please provide the following information:

- What changes you made:

- Why you made them, and:

- Any other useful context:

Make sure to follow the PR preparation steps in [CONTRIBUTING.md](../CONTRIBUTING.md#preparing-your-pr) before submitting your PR:

- [ ] format the codebase: from the root, run `yarn fmt:prettier`.
- [ ] update all snapshots (in core & CLI): from the root, run `yarn test:update`
- [ ] add Changeset entry: from the root, run `yarn g:changeset` and follow the CLI instructions. Alternatively, use the Changeset Github Bot to create the file.

2024-08-19 18:16 UTC, samijaber requested changes
I tested this logic in the angular playground, and it doesn't actually set the attribute in `ngOninit` because the element reference is `undefined` at that point:

```ng
import {Component, ElementRef, Renderer2, SimpleChanges, ViewChild} from '@angular/core';
import {bootstrapApplication} from '@angular/platform-browser';

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <div #elRef0>Hello world!</div>
  `,
})
export class PlaygroundComponent {
  @ViewChild("elRef0") elRef0!: ElementRef;

  attributes = {
    foo: 'bar',
    style: 'background-color: "red"'
  }
  
  setAttributes(el: HTMLElement, value: any) {
    console.log('setAttributes:', {el})
    if (!el) {
      return;
    }

    Object.keys(value).forEach((key) => {
      console.log('setting', {key, value})
      if (key.startsWith("on")) {
        this.renderer.listen(
          el,
          key.replace("on", "").toLowerCase(),
          value[key]
        );
      } else {
        this.renderer.setAttribute(el, key, value[key] ?? "");
      }
    });
  }

  constructor(private renderer: Renderer2) {}

  ngOnInit() {
    console.log('ngOninit:', {el: this.elRef0})
    this.setAttributes(this.elRef0?.nativeElement, this.attributes);
  }

  ngOnChanges(changes: SimpleChanges) {
      console.log('ngOnChanges:', {el: this.elRef0?.nativeElement})
    if (typeof window !== "undefined") {
      console.log('ngOnChanges (browser):', {el: this.elRef0?.nativeElement})
      this.setAttributes(this.elRef0?.nativeElement, this.attributes);
    }
  }
}

bootstrapApplication(PlaygroundComponent);
```

2024-08-19 18:16 UTC, samijaber commented on packages/core/src/generators/angular/helpers.ts
> +          );
we need to add logic to destroy these listeners:

- https://medium.com/claritydesignsystem/four-ways-of-listening-to-dom-events-in-angular-part-3-renderer2-listen-14c6fe052b59#e502
- https://stackoverflow.com/a/44454508


so we'll need to save the return value of every `this.renderer.listen()` call, and then call them on `ngOnDestroy`.

Not only that, we will also need to handle `ngOnChanges`, which AFAICS is going to keep adding listeners on every `ngOnChanges` call, quickly causing a memory leak.

2024-08-20 09:02 UTC, sidmohanty11 commented on packages/core/src/generators/angular/helpers.ts
> +          );
thank you! will add the check so that it destroys onUnMount.

> Not only that, we will also need to handle ngOnChanges, which AFAICS is going to keep adding listeners on every ngOnChanges call, quickly causing a memory leak.

oh yes, this will not be a mere replacement but a new event addition... but we still need a way to update event listeners on changes as any event binding may be updated while visual editing

2024-08-28 15:54 UTC, samijaber commented on packages/core/src/generators/angular/index.ts
> +    delete json.compileContext?.angular;
btw, you don't need to `delete` anything since the `json` is always cloned at the start of each generator, and not used outside of it afterwards.

2024-08-30 09:52 UTC, sidmohanty11 commented on packages/core/src/generators/angular/index.ts
> +    delete json.compileContext?.angular;
got it thanks, removed

2024-08-30 13:07 UTC, samijaber approved these changes
⚡

2024-09-02 08:39 UTC, sidmohanty11 commented on packages/core/src/generators/angular/helpers.ts
> +        this.renderer.setAttribute(el, key.toLowerCase(), target[key] ?? '');
this handles `autoPlay` -> `autoplay`, `playInline` -> `playinline` etc

2024-09-02 08:40 UTC, sidmohanty11 commented on packages/core/src/generators/angular/index.ts
> +          changesCode = `changes['${spreadCode.replace('this.', '')}']?.currentValue`;
the `|| {}` only works if we are destructuring props directly but if we are using a state it wont be present in the `changes` object so we would need to re-send the object (by keeping this part `undefined`)

2024-09-03 16:25 UTC, samijaber approved these changes

2024-09-03 16:39 UTC, merged