[FIXUP] passing wrong object for transforming refs
BuilderIO/mitosis pull request #1546
Opened 2024-09-04 12:01 UTC by newbie95

Added fixup for the [issue](https://github.com/BuilderIO/mitosis/issues/1150)

2024-09-25 20:16 UTC, samijaber commented
please create pull requests using our pull request template. it includes instructions and steps that you need to follow for your PR to be mergable to the repo.

https://github.com/BuilderIO/mitosis/blob/main/.github/pull_request_template.md

2024-09-25 20:17 UTC, samijaber requested changes
PR request template not followed: missing changeset and tests

2024-10-15 16:09 UTC, samijaber requested changes
Awesome, thanks! You can actually get rid of the new test: the existing snapshots cover your bugfix

2024-10-15 16:09 UTC, samijaber commented on packages/core/src/__tests__/test-generator.ts
> +  ref,
looking at the snapshot tests updates, I see many existing snapshots getting fixed by your PR.

You can remove this new `lit-ref.raw.tsx` test and its snapshot: there are existing tests that cover your fix! 🙏🏽

2024-10-15 17:24 UTC, newbie95 commented on packages/core/src/__tests__/test-generator.ts
> +  ref,
That's great to hear! I've removed the new test cases.

2024-10-15 19:36 UTC, merged