feat: refactor stencil generator to work properly with current version
BuilderIO/mitosis pull request #1547
Opened 2024-09-06 09:29 UTC by nmerget

## Description

Please provide the following information:

Refactored [Stencil](https://stenciljs.com/) generator to work with current Version.
The previous generator didn't work with all tests/examples.

Make sure to follow the PR preparation steps in [CONTRIBUTING.md](../CONTRIBUTING.md#preparing-your-pr) before submitting your PR:

- [x] format the codebase: from the root, run `yarn fmt:prettier`.
- [x] update all snapshots (in core & CLI): from the root, run `yarn test:update`
- [ ] add Changeset entry: from the root, run `yarn g:changeset` and follow the CLI instructions. Alternatively, use the Changeset Github Bot to create the file.

2024-09-20 13:36 UTC, nmerget commented
@samijaber Can I do anything else to support you with this?

2024-09-25 20:07 UTC, samijaber commented on packages/core/src/generators/angular/index.ts
> +    const childComponents: string[] = getChildComponents(json);
can we add a changeset for angular? this impacts the angular snapshots

2024-09-25 20:12 UTC, samijaber commented on packages/core/src/generators/stencil/generate.ts
> +    str = str.replaceAll(`props.`, `this.`);
we really want to avoid `replaceAll()`'s in the mitosis codebase. can you dig into what `props.*` instances aren't being handled properly by `processBinding`?

You can try using `replaceNodes` inside of `processBinding` (instead of, or in addition to `stripStateAndPropsRefs`). `stripStateAndPropsRefs` uses the deprecated `replaceIdentifiers` which has some issues. `replaceNodes` is more consistent

example of use: https://github.com/BuilderIO/mitosis/blob/main/packages/core/src/parsers/svelte/helpers/post-process.ts#L45-L53

2024-09-26 12:47 UTC, nmerget commented on packages/core/src/generators/stencil/generate.ts
> +    str = str.replaceAll(`props.`, `this.`);
Fixed. I just missed to use `processBinding` inside `blockToStencil`

2024-09-26 18:35 UTC, samijaber requested changes

2024-09-26 18:35 UTC, samijaber commented on packages/core/src/generators/stencil/collect-class-string.ts
> +    dynamicClasses.push(processBinding(json.bindings.class.code, processBindingOptions));
you shouldn't need to add `processBinding` all over a generator. This is exactly why I created the `CODE_PROCESSOR_PLUGIN` plugin: it groups all of this "code processing" logic into one centralized place. This means we will never forget to add our processing for one particular scenario.

I see we haven't added this plugin to stencil generator yet: we should do that and use `processBinding` there. Here's two examples in Svelte of how we use this plugin: https://github.com/BuilderIO/mitosis/blob/664f4a1342f91c1e96b088914420cd1074f8e35c/packages/core/src/generators/svelte/svelte.ts#L150-L185

2024-09-27 11:28 UTC, nmerget commented on packages/core/src/generators/stencil/collect-class-string.ts
> +    dynamicClasses.push(processBinding(json.bindings.class.code, processBindingOptions));
Ahh perfect, I saw this but didn't know when/how I should use it. I'll change it 👍

2024-09-30 06:36 UTC, nmerget commented on packages/core/src/generators/stencil/collect-class-string.ts
> +    dynamicClasses.push(processBinding(json.bindings.class.code, processBindingOptions));
@samijaber I changed it, looks very clean <3

Maybe it's a good idea to structure every generator like this? 
![image](https://github.com/user-attachments/assets/740b30c3-f124-4fae-99c5-031028e06b4c)

This would help to find parts for a generator way better then using a single file for `toComponent`, `toBlock` and `plugins`. What do you think?

2024-09-30 17:21 UTC, samijaber commented on packages/core/src/generators/stencil/collect-class-string.ts
> +    dynamicClasses.push(processBinding(json.bindings.class.code, processBindingOptions));
yes, our newer generators have been improved to have a more flat folder structure, bu the old ones are still stuck in one big file. Typically we have `state.ts`, `blocks.ts`, `generator.ts` and `types.ts` and some helpers.

open to ideas. I like your improvement, we can stick with that 👍🏽

2024-09-30 17:24 UTC, samijaber approved these changes
Amazing! looking at the stencil snapshots, lokos like tons of stuff got fixed :)

2024-09-30 17:24 UTC, samijaber commented on packages/core/src/generators/stencil/plugins/get-code-processor-plugins.ts
> +    // Strip types from any JS code that ends up in the template, because Svelte does not support TS code in templates.
```suggestion
```

2024-10-01 12:21 UTC, merged