feat: add typescript support for useStore<T>
BuilderIO/mitosis pull request #1555
Opened 2024-09-06 16:22 UTC by nmerget

## Description

Please provide the following information:

Add TypeScript support for `useStore<T>` for those generators:

- [x] React
- [ ] Angular
- [ ] Vue

Make sure to follow the PR preparation steps in [CONTRIBUTING.md](../CONTRIBUTING.md#preparing-your-pr) before submitting your PR:

- [ ] format the codebase: from the root, run `yarn fmt:prettier`.
- [ ] update all snapshots (in core & CLI): from the root, run `yarn test:update`
- [ ] add Changeset entry: from the root, run `yarn g:changeset` and follow the CLI instructions. Alternatively, use the Changeset Github Bot to create the file.

2024-09-27 20:44 UTC, samijaber requested changes
Awesome! I'm requesting changes to the React generator because the `any` default is bad, but otherwise LGTM 👍🏽

2024-09-27 20:44 UTC, samijaber commented on packages/core/src/generators/react/state.ts
> +    const stateType = options.typescript ? `<${stateVal.typeParameter ?? 'any'}>` : '';
adding `any` here is actually causing more harm than good: TypeScript is always able to infer the type on its own, and you're overriding that:

![CleanShot 2024-09-27 at 17 41 25@2x](https://github.com/user-attachments/assets/54050f85-5fee-47ff-a9f8-8a785e21d048)

if there is no `stateVal.typeParameter`, we should not do anything.

2024-09-27 20:54 UTC, samijaber commented on .changeset/quick-crabs-cough.md
> +feat: add typescript support for useStore (angular,react,vue)
I just documented our changset format so we all write them the same way moving forward: https://github.com/BuilderIO/mitosis/pull/1571

https://github.com/BuilderIO/mitosis/blob/7ac77ab2ffeb59b9ce82e515f4466b933c89701e/CONTRIBUTING.md#changeset-format

2024-09-30 08:28 UTC, nmerget commented on packages/core/src/generators/react/state.ts
> +    const stateType = options.typescript ? `<${stateVal.typeParameter ?? 'any'}>` : '';
Makes sense, I fixed it

2024-09-30 08:28 UTC, nmerget commented on .changeset/quick-crabs-cough.md
> +feat: add typescript support for useStore (angular,react,vue)
Yes, I saw it thank you.

Fixed it.

2024-09-30 08:32 UTC, nmerget commented on packages/core/src/__tests__/test-generator.ts
> +                      }
At the moment I test the implementation by createing a temporary test like this (example for vue):

![image](https://github.com/user-attachments/assets/a2e1457a-0613-412a-aa23-ceee7f1868e1)

Then I look at `packages/core/src/__tests__/test-generator.ts` to find the name of the test case to put it into `only: [...]`.

How do you test the code, is there any other way right now?

2024-09-30 17:31 UTC, samijaber commented on packages/core/src/__tests__/test-generator.ts
> +                      }
same as you, but i made a permanent file here: https://github.com/BuilderIO/mitosis/blob/main/packages/core/src/__tests__/local.test.ts

it's always skipped. I add the tests that i want into it and run `yarn test local`.

2024-09-30 17:31 UTC, samijaber commented on .changeset/quick-crabs-cough.md
> +[All] Add new snapshot tests to check if TypeScript works for ``useStore``
i wouldn't include testing improvements in the release notes

2024-09-30 17:32 UTC, samijaber commented on .changeset/quick-crabs-cough.md
> +[All] Add new snapshot tests to check if TypeScript works for ``useStore``
(unless they're huge test infra additions)

2024-09-30 17:32 UTC, samijaber commented on .changeset/quick-crabs-cough.md
> +[All] Add new snapshot tests to check if TypeScript works for ``useStore``
```suggestion
```

2024-09-30 17:33 UTC, samijaber approved these changes

2024-09-30 17:34 UTC, merged