implement jsx-callback-arrow-function rule
BuilderIO/mitosis pull request #180
Opened 2022-02-19 22:35 UTC by sahilmob

2022-03-03 18:02 UTC, steve8708 commented
This is awesome @sahilmob! @samijaber will take a look shortly. And in the meantime looks like you just need to run prettier to pass the build

From the project root:
```
npm install # if you haven't
npm run prettier -- --write .
```

then push up the changes

2022-03-07 20:55 UTC, samijaber requested changes
@sahilmob we had some issues with our CI: a `test` script was missing. I just merged https://github.com/BuilderIO/mitosis/pull/191. If you can pull the changes, your new tests will properly run in Github Actions now.

I manually ran `npx jest` locally and saw that one of the tests is failing (`use-state-var-declarator`). I'll finish looking over the other rules while you find what's wrong with that one :)

2022-03-07 22:31 UTC, samijaber reviewed
Looks fairly good. A few things to tweak, should be good afterwards :)

2022-03-07 22:31 UTC, samijaber commented on packages/eslint-plugin/src/rules/__tests__/no-var-declaration-in-jsx.ts
> +    // Doesn't affect variable declaration inside JXS attributes.
```suggestion
    // Doesn't affect variable declaration inside JSX attributes.
```

2022-03-07 22:31 UTC, samijaber commented on packages/eslint-plugin/src/rules/__tests__/css-no-vars.ts
> +    { ...opts, code: '<button/>', ...opts },
```suggestion
    { ...opts, code: '<button/>' },
```

2022-03-07 22:31 UTC, samijaber commented on packages/eslint-plugin/src/rules/only-default-function-and-imports.ts
> +                "Mitosis component file shouldn't contain anything other than import declamations, the component itself a default export or type declarations",
```suggestion
                "Mitosis component files should only contain import declarations, the component itself (in a default export), and type declarations",
```T

2022-03-07 22:31 UTC, samijaber commented on packages/eslint-plugin/src/rules/use-state-var-declarator.ts
> +                  'useState should be assigned to a variable called state exclusively',
```suggestion
                  'useState should be exclusively assigned to a variable called state',
```

2022-03-09 16:49 UTC, samijaber reviewed
@sahilmob I forgot to mention this in the initial review, but we also need some documentation on what these rules represent. See https://github.com/BuilderIO/mitosis/blob/main/packages/eslint-plugin/docs/rules/jsx-callback-arg-name.md as an example for the one we already have.

Should be able to quickly put those together based on the tests & descriptions you've written 🙏🏽

2022-03-15 02:31 UTC, steve8708 commented
this is awesome @sahilmob, looks great!

2022-03-15 15:13 UTC, merged

2022-03-15 15:50 UTC, sahilmob commented
Thanks. Looking forward to more contributions. 🚀 🚀 🚀