allow multiple onUpdate hooks
BuilderIO/mitosis pull request #248
Opened 2022-03-26 20:29 UTC by sahilmob

fixes #241

2022-03-26 20:32 UTC, sahilmob commented
@samijaber I guess I have implemented the required changes for all generators, however, for vue, I can't get the tests to pass. Would you mind taking a look?

2022-03-28 15:16 UTC, samijaber commented on packages/core/src/generators/vue.ts
> +        });
This `onUpdatePlugin` code should iterate over `component.hooks.onUpdate`, but _only_ apply to a hook if `deps` exists. You can do that by adding a 

`if (hook.deps)` check within the `forEach`

2022-03-28 15:16 UTC, samijaber commented on packages/core/src/generators/vue.ts
> +                      `,
For this, we need to split `component.hooks.onUpdate` into two:

```ts
const onUpdateWithDeps = component.hooks.onUpdate.filter(hook => hook.deps)
const onUpdateWithoutDeps = component.hooks.onUpdate.filter(hook => !hook.deps)
```

and then use the first one for `watch`, and the second one for the `updated()`

```tsx
${onUpdateWithoutDeps.length
  ? `updated() {
        ${onUpdateWithoutDeps.map(hook) => /**/}
      }`
  :  ''
}

${onUpdateWithDeps.length
  ? `watch: {
        ${onUpdateWithDeps.map(hook, index) => /**/}
      }`
  :  ''
}

```

I think that should get the code in a good place. You will need to update the snapshots since the name of the hooks now has `_index` appended to it.

2022-03-28 15:28 UTC, samijaber commented on packages/core/src/generators/vue.ts
> +        component.hooks.onUpdate.forEach((hook, index) => {
This `onUpdatePlugin` code should iterate over `component.hooks.onUpdate`, but only apply to a hook if `deps` exists.

```ts
post: (component) => {
  component.hooks.onUpdate.filter(hook => hook.deps).forEach(...
  )
}
```

2022-03-28 21:50 UTC, samijaber requested changes

2022-03-28 21:50 UTC, samijaber commented on packages/core/src/generators/vue.ts
> +            ] = `${ON_UPDATE_HOOK_NAME}_${index} () {
The `get` prefix was removed but it's needed to tell Mitosis that this is a getter method:

```suggestion
            ] = `${methodLiteralPrefix}get ${ON_UPDATE_HOOK_NAME}_${index} () {
```

2022-03-28 21:50 UTC, samijaber commented on packages/core/src/generators/vue.ts
> +              ON_UPDATE_HOOK_NAME + `_${index}`
Since we do this ``ON_UPDATE_HOOK_NAME + `_${index}` `` logic 3 times, Can we extract it to a helper and re-use it?

```ts
const getOnUpdateHookName = (index: string) => ON_UPDATE_HOOK_NAME + `_${index}`
```

2022-03-28 21:50 UTC, samijaber commented on packages/core/src/generators/vue.ts
> +            )}
The `map` output automatically joins with `,`, which is giving us invalid code (see the `vue` test snapshots).

```suggestion
            ).join('\n')}
```

2022-03-28 21:50 UTC, samijaber commented on packages/core/src/generators/vue.ts
> +              .join(';')}
I believe we want a comma here! Otherwise, we get:

```
  watch: {
      onUpdateHook_0() {
            console.log('Runs when a or b changes', this.a, this.b)
            }
          ;onUpdateHook_1() {
            console.log('Runs when c or d changes', this.c, this.d)
            }
    },
```
Which is invalid JS. See the Vue test snapshot.

```suggestion
              .join(',')
```

2022-03-28 22:14 UTC, sahilmob commented
@samijaber I resolved all the issues, however, with those fixes, the tests weren't passing. I get an error related to Babel version.
```
    console.error
      Error parsing code:
       onUpdateHook_0 () {
                  return `${this.a}|${this.b}`
                } 
       Error: [BABEL] unknown: Requires Babel "^7.0.0-0", but was loaded with "7.14.5". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing: "base$0")
          at Object.assertVersion (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/@babel/core/lib/config/helpers/config-api.js:92:15)
          at /Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/@babel/preset-typescript/src/index.js:6:7
          at /Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/@babel/helper-plugin-utils/lib/index.js:22:12
          at sync (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/@babel/core/lib/gensync-utils/async.js:37:25)
          at sync (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/gensync/index.js:182:19)
          at /Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/gensync/index.js:210:24
          at Generator.next (<anonymous>)
          at /Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/@babel/core/lib/config/full.js:217:21
          at Generator.next (<anonymous>)
          at Function.<anonymous> (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/@babel/core/lib/gensync-utils/async.js:24:3)
          at Generator.next (<anonymous>)
          at evaluateSync (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/gensync/index.js:251:28)
          at Function.sync (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/gensync/index.js:89:14)
          at sync (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/@babel/core/lib/gensync-utils/async.js:67:25)
          at sync (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/gensync/index.js:182:19)
          at onFirstPause (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/gensync/index.js:210:24)
          at Generator.next (<anonymous>)
          at cachedFunction (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/@babel/core/lib/config/caching.js:66:46)
          at cachedFunction.next (<anonymous>)
          at loadPresetDescriptor (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/@babel/core/lib/config/full.js:313:43)
          at loadPresetDescriptor.next (<anonymous>)
          at recursePresetDescriptors (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/@babel/core/lib/config/full.js:114:30)
          at recursePresetDescriptors.next (<anonymous>)
          at /Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/@babel/core/lib/config/full.js:191:21
          at Generator.next (<anonymous>)
          at loadFullConfig (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/@babel/core/lib/config/full.js:144:5)
          at loadFullConfig.next (<anonymous>)
          at Function.transform (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/@babel/core/lib/transform.js:23:45)
          at transform.next (<anonymous>)
          at evaluateSync (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/gensync/index.js:251:28)
          at Function.sync (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/gensync/index.js:89:14)
          at Object.transform (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/@babel/core/lib/transform.js:34:54)
          at babelTransform (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:15:16)
          at /Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:63:38
          at apply (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/lodash/lodash.js:487:27)
          at /Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/lodash/lodash.js:15326:16
          at apply (/Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/lodash/lodash.js:489:27)
          at /Users/sahilmobaidin/Desktop/mitosis/packages/core/node_modules/lodash/lodash.js:6627:16
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:62:16)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          at babelTransformExpression (/Users/sahilmobaidin/Desktop/mitosis/packages/core/src/helpers/babel-transform.ts:104:40)
          [...]

2022-03-29 19:59 UTC, samijaber reviewed
Excellent 🏆 . 

Just some small thing I noticed in `map-refs.ts` and then this is good to merge 😄

2022-03-29 19:59 UTC, samijaber commented on packages/core/src/helpers/map-refs.ts
> +  // }
```suggestion

```

2022-03-29 19:59 UTC, samijaber commented on packages/core/src/helpers/map-refs.ts
> +      }
We can avoid the need for the type-casts here if we create a `const hooks = component.hooks[key];` before the if-else logic

```suggestion
    const hooks = component.hooks[key];
    if (Array.isArray(hooks)) {
      hooks.forEach((hook) => {
        if (hook.code) {
          hook.code = replaceRefsInString(hook.code, refs, mapper);
        }
      });
    } else {
      const hookCode = hooks?.code;
      if (hookCode) {
        hooks.code = replaceRefsInString(hookCode, refs, mapper);
      }
    }
```

2022-03-29 21:29 UTC, samijaber approved these changes
🙏🏽

2022-03-29 21:29 UTC, merged