Fix parser jsx custom event argument name
BuilderIO/mitosis pull request #323
Opened 2022-05-08 03:12 UTC by PatrickJS

## Description

Add a short description of:
- what changes you made, 
- why you made them, and 
- any other context that you think might be helpful for someone to better understand what is contained in this pull request. 

This sort of information is useful for people reviewing the code, as well as anyone from the future trying to understand why changes were made or why a bug started happening.

2022-05-09 12:26 UTC, samijaber requested changes

2022-05-09 12:26 UTC, samijaber commented on packages/core/src/parsers/jsx.ts
> +        }
This isn't quite the right place for this logic. I recently documented `properties` vs `bindings`: https://github.com/BuilderIO/mitosis/blob/ccb51aed001181d55030011379175f58c478fea7/packages/core/src/types/mitosis-node.ts#L7-L30

A better approach is to modify the `bindings` signature to look something like:

```ts
bindings: {
  code: string;
  arguments?: string[];
}
```

And move this logic to the `reduce` right below in `bindings`. 

This will also greatly clean up how we consume these arguments in the generators.

You alluded to something similar in https://github.com/BuilderIO/mitosis/issues/326

2022-05-09 12:26 UTC, samijaber commented on docs/gotchas.md
> +### Callback implicitly have an "$event" arg in Angular
This caveat should remain general to all generators, since this PR only fixes it for a couple of them. Most of them still rename the argument to `event`

2022-05-09 14:18 UTC, PatrickJS commented on packages/core/src/parsers/jsx.ts
> +        }
bindings: {
  onClick: string;
  arguments?: string[];
}

my issue is if we have more than one event.

bindings: {
  onClick: string;
  onInput: string
  _arguments_onClick?: string[];
  _arguments_onInput?: string[];
}

After looking into the code I'm thinking I can also store this in meta.

Ideally we want 
bindings: {
  onClick: {
    arguments: string[],
    code: string
  };
}

2022-05-09 14:20 UTC, PatrickJS commented on packages/core/src/parsers/jsx.ts
> +        }
if everyone is okay with adding scope to the nodes it would clean up a lot of code and I can just refactor everything to use it

2022-05-09 15:10 UTC, samijaber commented on packages/core/src/parsers/jsx.ts
> +        }
Sorry, my types example was missing the index signature! I meant to say the same thing you did:

```ts
bindings: {
  [index: string]: {
    arguments: string[],
    code: string
  };
}
```

> if everyone is okay with adding scope to the nodes 

I personally prefer we keep the change small and located to just the `bindings` properties: that's a similar API/interface to what we've done for `onUpdate` hooks and their `dependencies` array: https://github.com/BuilderIO/mitosis/blob/ccb51aed001181d55030011379175f58c478fea7/packages/core/src/types/mitosis-component.ts#L34

2022-05-09 15:21 UTC, steve8708 commented on packages/core/src/parsers/jsx.ts
> +        }
I think changing bindings to code & arguments is a good idea. and agreed in theory properties shouldn't need this as it only takes simple string values

2022-05-09 21:05 UTC, PatrickJS commented
I'l refactor it to 
```
bindings: {
  [index: string]: {
    arguments: string[],
    code: string
  };
}
```
and remove the docs edit

2022-05-17 01:00 UTC, PatrickJS commented
I'm closing this to create an issue https://github.com/BuilderIO/mitosis/issues/351. I'll end up doing this if no one else picks it up.

2022-05-17 01:00 UTC, closed without merging