fix(webcomponent): useRef
BuilderIO/mitosis pull request #377
Opened 2022-05-20 20:11 UTC by PatrickJS

## Description
useRef

2022-05-20 20:15 UTC, PatrickJS commented on packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap
> +      \\"[data-ref='MyMasicRefComponent-inputRef']\\"
might be losing context here

2022-05-20 21:07 UTC, PatrickJS commented on packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap
> +      \\"[data-ref='MyMasicRefComponent-inputRef']\\"
Actually if ref is used in a function it's lost since this is state object

2022-05-23 13:37 UTC, PatrickJS commented
I need to rebase

2022-05-23 13:44 UTC, PatrickJS commented on packages/core/src/parsers/jsx.ts
> +                ref: generate(valueNode).code,
I need a way to get the code for when the user is referencing a factory function to create the context

2022-05-23 13:45 UTC, PatrickJS commented on packages/core/src/types/mitosis-component.ts
> +    }; // TODO: support non object values
ref is a workaround to support non-objects

2022-05-23 13:46 UTC, PatrickJS commented
@decadef20 when you are available can you review this PR?

2022-05-23 13:47 UTC, PatrickJS commented on packages/core/src/__tests__/__snapshots__/webcomponent.test.ts.snap
> +      this.state.onChange;
I will find a way to fix this later

2022-05-23 15:40 UTC, decadef20 commented on packages/core/src/__tests__/__snapshots__/html.test.ts.snap
> +      if (el?.context) {
`renderTextNode` is never used here.

2022-05-23 18:20 UTC, PatrickJS commented on packages/core/src/__tests__/__snapshots__/html.test.ts.snap
> +      if (el?.context) {
I'll update `componentToHtml` can you check `componentToCustomElement`

2022-05-23 18:35 UTC, PatrickJS commented on packages/core/src/__tests__/__snapshots__/html.test.ts.snap
> +      if (el?.context) {
ok I fixed it https://github.com/BuilderIO/mitosis/pull/377/commits/de9698e9b396dbd05fe8294bbc5bb00ba502d538

2022-05-24 09:39 UTC, decadef20 approved these changes
LGTM

2022-05-26 20:26 UTC, samijaber submitted a review, later dismissed

2022-05-26 20:26 UTC, samijaber commented on packages/core/src/parsers/jsx.ts
> +                ref: generate(valueNode).code,
This is causing us to duplicate context data every time. I think we should store either `value` or `ref`, depending on what `valueNode` is.

Pseudocode:

```ts
if (valueNode) {
  if (types.isObjectExpression(valueNode)) {
    return { value: parseStateObject(valueNode) }
  } else {
    return { ref: generate(valueNode).code }
  }
} else {
  return undefined
}
```

And the type of Context would then look something like:

```ts
type ContextSet = { name: string; } & ({ value: JSONObject } | { ref: any } | undefined);
```

2022-05-26 21:08 UTC, PatrickJS commented on packages/core/src/parsers/jsx.ts
> +                ref: generate(valueNode).code,
yeah I'll do that until we figure out a better way to handle this

2022-05-27 19:29 UTC, samijaber requested changes
Everything for context looks good now, but you broke `onInit` for React.

I suggest you move that out if you want to get the rest of the code merged without blocking it.

2022-05-27 19:29 UTC, samijaber commented on packages/core/src/parsers/jsx.ts
> +                  const value = parseStateObject(valueNode) as JSONObject;
Isn't this cast unnecessary?

```suggestion
                  const value = parseStateObject(valueNode);
```

2022-05-27 19:29 UTC, samijaber commented on packages/core/src/parsers/jsx.ts
> +                  const ref = generate(valueNode).code as string;
Same here, unnecessary cast:

```suggestion
                  const ref = generate(valueNode).code;
```

2022-05-27 19:29 UTC, samijaber commented on packages/core/src/__tests__/__snapshots__/react.test.ts.snap
> +  console.log(\\"set defaults with props\\");
Pretty sure your changes to `onInit` logic broke it: you're now setting state on every single render.

2022-05-27 19:29 UTC, samijaber commented on packages/core/src/generators/react.ts
> +          ? `${!onInitLocalVars ? '' : ';(function () {'}
I don't really understand this change fully, but I know that removing `useEffect` breaks the implementation of `onInit`, as you're now running the code on every single render, not just on init.

Wanna revert this change and move it to a separate PR so it's not blocking the rest of this PR?

2022-05-27 20:14 UTC, PatrickJS commented on packages/core/src/generators/react.ts
> +          ? `${!onInitLocalVars ? '' : ';(function () {'}
onMount is preferred. onInit is now only meant to work around some of the problems with useState. we can't set default values with props so this is the only place to do it

2022-05-27 20:16 UTC, PatrickJS commented on packages/core/src/parsers/jsx.ts
> +                  const value = parseStateObject(valueNode) as JSONObject;
`parseStateObject` returns `any`

2022-05-27 20:17 UTC, PatrickJS commented on packages/core/src/generators/react.ts
> +          ? `${!onInitLocalVars ? '' : ';(function () {'}
https://github.com/BuilderIO/mitosis/issues/388#issuecomment-1136027557

2022-05-27 20:41 UTC, PatrickJS commented on packages/core/src/generators/react.ts
> +          ? `${!onInitLocalVars ? '' : ';(function () {'}
I put it under an experimental flag

2022-05-30 14:16 UTC, samijaber commented on packages/core/src/generators/react.ts
> +              options?.experimental?.localOnInit
Just to re-iterate: having side-effect code run in the `render` body of a React component is a very bad idea, and not what we want to do. It's dangerous and should be avoided. Re-renders will cause your component to misbehave in many ways, and they will never work.

If I copy the snapshot example you had in the previous commit into Stackblitz, it crashes due to infinite re-renders: https://stackblitz.com/edit/react-ts-jisvkk?file=App.tsx

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/1393142/171009992-90b22fe7-3702-47ea-ba3b-51707fa59901.png">


The `render` body should always be a pure function without side effects. Any side effect should be moved inside of a React hook of some kind. In the case of wanting to solve https://github.com/BuilderIO/mitosis/issues/388, we'd want to figure out a way to move the state initialization code inside of `useState(initValue)`.

On one hand, I'm OK keeping this code in since it's behind an experimental flag, on the other, it won't ever work as we expect so I'm not sure why we'd want to keep it

2022-05-30 17:13 UTC, PatrickJS commented on packages/core/src/generators/react.ts
> +              options?.experimental?.localOnInit
we can change onInit to be useEffect with no deps until useState is refactored first.
(in this case being able to set `initValue` of `useState(initValue)` because we want to set default values in Mitosis useState).

onInit should only exist until Mitosis handles everything correctly 

The end goal is going towards having local variables and the dev not having to setup memo/useMemo/useCallback (perf step required by every react dev)

The original component was trying to avoid using `useState` but had to because of the current Mitosis limits

2022-05-31 13:48 UTC, samijaber approved these changes

2022-05-31 13:48 UTC, samijaber commented on packages/core/src/generators/react.ts
> +
unused code

```suggestion
```

2022-05-31 15:01 UTC, merged