feat(core): useRef, compileAwayPackages
BuilderIO/mitosis pull request #439
Opened 2022-06-03 04:11 UTC by PatrickJS

## Description
fix: https://github.com/BuilderIO/mitosis/issues/438
fix: https://github.com/BuilderIO/mitosis/issues/437
fix: https://github.com/BuilderIO/mitosis/issues/400
fix: https://github.com/BuilderIO/mitosis/issues/186

2022-06-03 04:32 UTC, PatrickJS commented on packages/core/src/index.ts
> +export const useRef = <T>(obj?: null | undefined | T) => obj as unknown as T;
@samijaber I need some typing help here. I want useRef to be valid if no arguments or type params are added

`const something = useRef()`

2022-06-03 04:33 UTC, PatrickJS commented on packages/core/src/parsers/jsx.ts
> +  key: babel.types.Expression | babel.types.PrivateName | any,
for some reason this started to error without `any`. I'm not sure what typescript problem was added that can cause this

2022-06-03 04:34 UTC, PatrickJS commented on packages/core/src/generators/react.ts
> -  mapRefs(json, (refName) => `${refName}?.current`);
it turned out `?.current` was invalid and the real issue was not having `useRef(null)`

2022-06-03 04:49 UTC, PatrickJS commented on packages/core/src/__tests__/data/basic-ref.raw.tsx
> +  const inputNoArgRef = useRef(undefined);
I'm not sure how to type this correctly

2022-06-03 15:52 UTC, samijaber commented on packages/core/src/index.ts
> +export const useRef = <T>(obj?: null | undefined | T) => obj as unknown as T;
Ugh, wrote a comment but it got erased somehow

Why do we want to make no-arguments a valid format? A reference needs to have some sort of default initial value, and it is far better for the end-user to provide that explicitly, rather than we do something implicit and then fiddle with types etc.

That would follow React's API as well: whatever type is provided to `useRef` is the type of the reference, and the user has to match that:

```suggestion
export const useRef = <T>(obj:T) => obj;
```

2022-06-03 15:56 UTC, samijaber commented on packages/core/src/index.ts
> +export const useRef = <T>(obj?: null | undefined | T) => obj as unknown as T;
It will also vastly simplify our parser and generators code, which in this PR involve a bunch of code to figure out if this is a dom ref or not, to then figure out that an initial `null` needs to be set. 

I think we should just do what React does and keep things simple.

2022-06-03 15:57 UTC, samijaber requested changes
Requesting changes because I think that the implementation of `useRef` should not handle implicit initial default values, and instead require that information upfront explicitly from the user.

2022-06-03 16:07 UTC, PatrickJS commented on packages/core/src/index.ts
> +export const useRef = <T>(obj?: null | undefined | T) => obj as unknown as T;
React allows for undefined its just for DOM refs it should be set to null

2022-06-07 19:18 UTC, samijaber commented on packages/core/src/index.ts
> +export const useRef = <T>(obj?: null | undefined | T) => obj as unknown as T;
I missed the notification for this last comment.

Do you still want to allow no args if the type args are specified?

2022-06-07 19:49 UTC, PatrickJS commented
@samijaber can you review it now?

2022-06-07 20:13 UTC, samijaber commented
@PatrickJS Looking now

2022-06-07 20:44 UTC, samijaber approved these changes

2022-06-07 20:44 UTC, samijaber commented on packages/core/src/helpers/get-props-ref.ts
> +      }
No need to loop over every binding here when we just need `ref`:

```suggestion
      const binding = item.bindings.ref;
      const regexp = /(.+)?props\.(.+)( |\)|;|\()?$/;
      if (binding && regexp.test(binding.code)) {
        const match = regexp.exec(binding.code);
        const _prop = match?.[2];
        if (_prop) {
          prop = _prop;
        }
        if (shouldRemove) {
          delete item.bindings.ref;
        }
        has = true;
        this.stop();
      }
```

2022-06-07 21:11 UTC, merged