fix(qwik): improve statement detection
BuilderIO/mitosis pull request #651
Opened 2022-08-18 22:47 UTC by mhevery

## Description

Add a short description of:
- what changes you made, 
- why you made them, and 
- any other context that you think might be helpful for someone to better understand what is contained in this pull request. 

This sort of information is useful for people reviewing the code, as well as anyone from the future trying to understand why changes were made or why a bug started happening.

2022-08-18 22:57 UTC, steve8708 approved these changes

2022-08-19 23:02 UTC, steve8708 approved these changes

2022-08-22 16:54 UTC, samijaber requested changes

2022-08-22 16:54 UTC, samijaber commented on README.MD
> +| qwik    | :white_check_mark: | :x:                |
This PR causes a regression. Any idea why?

2022-08-22 16:54 UTC, samijaber commented on README.MD
> +| qwik    | :white_check_mark: | :x:                |
(oh my god this is the first time that our e2e tests catch a regression, absolutely amazing to witness this live. Thanks @kylecordes 🏆 )

2022-08-24 22:54 UTC, mhevery commented on e2e/e2e-qwik/package.json
> +  "typeX": "module"
removed

2022-08-24 23:36 UTC, merged