Feat/653 vue generate composition api
BuilderIO/mitosis pull request #665
Opened 2022-08-24 20:32 UTC by raymondmuller

## Description

Issue #653 

Add composition API as an **option** to the Vue generator. It still defaults to the options API for now on this branch as this probably needs some more testing, though I think it is in a good state to get out there for others to try it and give feedback. It is my first time writing (part of a) generator here so I might have missed something :)

This also solves #582 , at least for the composition API script. 
While Vue does support TypeScript usage with Options API, it is recommended to use Vue with TypeScript via Composition API as it offers simpler, more efficient and more robust type inference, and you get type based declarations.

This looks like: 

- Types only

``` 
interface Props {
  conditionA: boolean;
  conditionB: boolean;
}
const props = defineProps<Props>();
```

- With default values
```
export interface ButtonProps {
  attributes?: any;
  text?: string;
  link?: string;
  openLinkInNewTab?: boolean;
}
const props = withDefaults(defineProps<ButtonProps>(), {
  text: "default text",
  link: "https://builder.io/",
  openLinkInNewTab: false,
});
```

I chose to use the <script setup> as (apart from my own preference) it is the recommended syntax per the Vue docs 

**<script setup> is a compile-time syntactic sugar for using Composition API inside Single-File Components (SFCs). It is the recommended syntax if you are using both SFCs and Composition API. It provides a number of advantages over the normal <script> syntax:**
- More succinct code with less boilerplate
- Ability to declare props and emitted events using pure TypeScript
- Better runtime performance (the template is compiled into a render function in the same scope, without an intermediate proxy)
- Better IDE type-inference performance (less work for the language server to extract types from code)

_source: https://vuejs.org/api/sfc-script-setup.html_

Note that defineProps and defineEmits are compiler macros only usable inside <script setup>. **They do not need to be imported,** and are compiled away when <script setup> is processed ,which is why they are not added the the `vueImports` array.

This PR also adds defineComponent to the options API script as it is supported and in their words "A type helper for defining a Vue component with type inference." and seems like a good thing to have.

2022-08-24 20:49 UTC, samijaber reviewed
This is huge! Thanks @raymondmuller. Will take a look at this very soon and give feedback :)

2022-08-29 16:32 UTC, samijaber commented on packages/core/src/generators/vue.ts
> +            require('prettier/parser-typescript'),
Would you mind adding this in a separate PR first? It caused a huge (highly positive!) change in the Vue snapshot tests, but it makes it hard to see if the rest of this PR introduced changes to the Options API output

2022-08-29 16:55 UTC, raymondmuller commented on packages/core/src/generators/vue.ts
> +            require('prettier/parser-typescript'),
Here you go: https://github.com/BuilderIO/mitosis/pull/679

2022-08-29 17:14 UTC, samijaber commented on packages/core/src/generators/vue.ts
> +            require('prettier/parser-typescript'),
Sweet! Merged it. Whenever you can, merge `main` into this branch 🙏🏽

2022-08-29 18:38 UTC, raymondmuller commented on packages/core/src/generators/vue.ts
> +            require('prettier/parser-typescript'),
Done

2022-08-29 20:12 UTC, samijaber commented on packages/core/src/generators/vue.ts
> +    function generateCompositionApiScript() {
Would it be possible to move `generateCompositionApiScript` and `generateOptionsApiScript` outside of the scope of the main generator function? Explicitly providing props to them will make the code a lot less tangled together 🙏🏽

2022-08-29 21:00 UTC, raymondmuller commented on packages/core/src/generators/vue.ts
> +    function generateCompositionApiScript() {
Done (https://github.com/BuilderIO/mitosis/pull/665/commits/83b2e9eb7182bedbaa05badd5305551d73e88e57)

2022-08-29 21:06 UTC, samijaber requested changes
I see from the snapshots that function generation is broken. 

One good way to test this is to tweak our e2e tests here: https://github.com/BuilderIO/mitosis/blob/2d760644b9b91b22486a9c3c6349403d14f8d993/e2e/e2e-app/mitosis.config.js#L48-L49

Such that Vue 3 uses this new composition API (or Vue 2, doesn't matter!) Then the e2e test will make sure the code is valid, compiles, and can actually pass e2e playwright tests

2022-08-30 11:56 UTC, samijaber reviewed
@raymondmuller This looks great! Thanks for the updates.

Looks like e2e tests are still failing for the vue3 Composition API code though.

2022-08-30 21:08 UTC, raymondmuller commented
> @raymondmuller This looks great! Thanks for the updates.
> 
> Looks like e2e tests are still failing for the vue3 Composition API code though.

Passing now!

2022-08-31 12:48 UTC, samijaber commented on packages/core/src/generators/vue.ts
> +    let regexpStr = `((this\\.)?${ref})\\b`;
We want to avoid using regexes for manipulating properties, as they're hard to maintain and have caused us lots of issues in the past. It's better to use an AST like babel's to transform the appropriate nodes.

We have 2 helpers to handle this type of stuff:

- `replaceIdentifiers` for simple use-cases: https://github.com/BuilderIO/mitosis/blob/2d760644b9b91b22486a9c3c6349403d14f8d993/packages/core/src/helpers/replace-identifiers.ts#L4

- `babelTransformExpression` for more complex ones (used internally by `replaceIdentifiers`): https://github.com/BuilderIO/mitosis/blob/2d760644b9b91b22486a9c3c6349403d14f8d993/packages/core/src/helpers/babel-transform.ts#L87


https://astexplorer.net/ is a useful tool to test out your transform and make sure it behaves as expected, or to learn what types of nodes you want to change. There are also a handful of examples in the codebase of using these helpers, that should give you an idea of how they use.

2022-09-01 15:04 UTC, samijaber commented on packages/core/src/generators/vue.ts
> +      console.log({ path });
```suggestion

```

2022-09-01 15:57 UTC, samijaber approved these changes
Absolutely fantastic contribution. Thank you @raymondmuller 🏆 🏆 🏆

2022-09-01 15:57 UTC, merged