Dynamically loading test blocks
BuilderIO/mitosis pull request #75
Opened 2021-03-09 12:34 UTC by luislpv22

Some progress made on issue #36

2021-03-16 19:12 UTC, mandx requested changes
I added some minor suggestions, in general this is a great starting point. I'll look into why the tests are failing; looks like for some reason no code is being transpiled, so code that expect non-empty strings is crashing.

2021-03-16 19:12 UTC, mandx commented on packages/core/src/__tests__/snapshots.test.ts
> +      const jsx: string = require(data.file);
I don't think we need to use `require` and invoke Node's module resolution algorithm, using `fs.readFileSync` should be enough, something like:
```suggestion
      const jsx = fs.readFileSync(data.file, 'utf8');
```

2021-03-28 23:43 UTC, luislpv22 commented
I've added your suggestions. Those are the blocks failing in tests:

 - All parsers › builder-render-block

```js
SyntaxError: JSON5: invalid end of input at 1:1

      490 |   );
      491 |   try {
    > 492 |     return JSON5.parse(toParse);
```
 - All parsers › builder-render-content

```js
SyntaxError: JSON5: invalid end of input at 1:1

      490 |   );
      491 |   try {
    > 492 |     return JSON5.parse(toParse);
```
- Html parser › form

```js
SyntaxError: unknown: Unexpected token, expected ";" (1:12)

    > 1 | let _ = get submissionState() {
        |             ^
      2 |   return Builder.isEditing && props.previewState || state.state;
      3 | }
```
- Html parser › columns

```js
SyntaxError: unknown: Unexpected token, expected ";" (3:13)

      1 | let _ = // TODO: These methods are not used right now, but they will be when
      2 | // support for dynamic CSS lands
    > 3 | getColumns() {
        |              ^
```

2021-03-29 18:06 UTC, mandx commented
Thanks @luislpv22 I'll take another look later today :)

2021-06-22 16:50 UTC, steve8708 commented
hey @mandx - any update here?

2021-06-22 17:23 UTC, mandx commented
@luislpv22 Looks like this PR has diverged a lot from the main branch; I'll suggest two things to get this restarted:

- Start over with a new/fresh branch, copy code as needed from this branch.
- Try make _additive_ changes, that is, let's introduce new unit-tests modules/files/snapshots instead of overwriting existing ones; worst case, we would be testing the same thing twice, but this will allow avoiding rebase/merge hell since the new PR will be mostly adding code instead of modifying existing code. We can always remove duplicated tests in a secondary PR.

2021-08-16 15:12 UTC, steve8708 commented
closing out due to inactivity to keepour PR list clean, please feel free to reopen @luislpv22 if you'd like to continue on this

2021-08-16 15:12 UTC, closed without merging