refactor(angular): angular component metadata generation
BuilderIO/mitosis pull request #750
Opened 2022-09-22 21:48 UTC by g-cheishvili

## Description

Add a short description of:
- Instead of having values in string moved them to Object
- Now it is in Object and can be more or less better overridden by the user
- Also, touched a bit `imports` generation

2022-09-22 22:08 UTC, samijaber approved these changes
Thanks for this!

2022-09-22 22:11 UTC, samijaber commented
you'll need to run `fmt:prettier` at the repo root to fix your PR

2022-09-22 22:29 UTC, g-cheishvili commented
Yeah, noticed. I am off from PC now, its 2:30 am here, will do tomorrow

2022-09-23 12:52 UTC, samijaber requested changes

2022-09-23 12:52 UTC, samijaber commented on packages/core/src/generators/angular.ts
> +      ...(css.length ? { styles: `\`${indent(css, 8)}\`` } : {}),
You removed the `[]` brackets in this string, this breaks the rendering of the styles property. you can see that the snapshot tests are all shifted.

```suggestion
      ...(css.length ? { styles: `[\`${indent(css, 8)}\`]` } : {}),
```

Make sure to run `yarn snapupdate` in `packages/core` locally to update test snapshots and see if there are changes there

2022-09-23 13:57 UTC, samijaber approved these changes
Awesome, welcome to Mitosis! ⚡

2022-09-23 13:57 UTC, merged