fix: camelcase attributes for react output
BuilderIO/mitosis pull request #844
Opened 2022-10-25 20:14 UTC by chadalen

2022-10-25 20:16 UTC, alujs approved these changes

2022-10-25 20:19 UTC, PatrickJS approved these changes

2022-10-25 20:24 UTC, samijaber requested changes

2022-10-25 20:24 UTC, samijaber commented on packages/core/src/__tests__/react.test.ts
> +  });
Please add this test to this object instead, so its tested by every generator: https://github.com/BuilderIO/mitosis/blob/07fab0c4ed332fde2fa9b56e10eb9f4816c237d1/packages/core/src/__tests__/shared.ts#L96

then run `yarn snapupdate`

2022-10-26 13:14 UTC, chadalen commented on packages/core/src/__tests__/react.test.ts
> +  });
Done

2022-10-26 15:29 UTC, samijaber approved these changes

2022-10-26 15:29 UTC, merged