Fix/default props function type lost
BuilderIO/mitosis pull request #896
Opened 2022-11-11 13:08 UTC by kingzez

## Description

Add a short description of:
- what changes you made, 
- why you made them, and 
- any other context that you think might be helpful for someone to better understand what is contained in this pull request. 

This sort of information is useful for people reviewing the code, as well as anyone from the future trying to understand why changes were made or why a bug started happening.

Fix https://github.com/BuilderIO/mitosis/issues/847

2022-11-14 16:30 UTC, samijaber requested changes
Amazing, thank you for this PR!

Just need to fix the issue with the trailing `}` being removed in the JSX parser.

2022-11-14 16:30 UTC, samijaber commented on packages/core/src/__tests__/__snapshots__/parse-jsx.test.ts.snap
> +      "code": "() => {",
This doesn't look right...it's missing `}` from the end 😮

2022-11-14 16:50 UTC, kingzez commented on packages/core/src/parsers/jsx/function-parser.ts
> +      .replace(/}$/, '');
@samijaber  I  trailing } here, I follow your [issues tips](https://github.com/BuilderIO/mitosis/issues/847#issuecomment-1307439504), I thought it should be done that way,  I change it later ^-^

2022-11-14 17:40 UTC, samijaber commented on packages/core/src/parsers/jsx/function-parser.ts
> +      .replace(/}$/, '');
Yup, sorry for that! Mistake on my part

2022-11-14 17:46 UTC, kingzez commented on packages/core/src/parsers/jsx/function-parser.ts
> +      .replace(/}$/, '');
Hahaha，it's my fault

2022-11-14 17:59 UTC, samijaber commented on packages/core/src/parsers/jsx/function-parser.ts
> +          [i.key?.name]: processDefaultPropsValue(i.value),
Actually, I recently merged logic that handles all of this logic cleanly: `parseStateObjectToMitosisState`

You can simplify this function and write:

```ts
  if (types.isObjectExpression(firstArg)) {
    component.defaultProps = parseStateObjectToMitosisState(firstArg)
  }
```

If you don't mind doing that, would be amazing 🙏🏽

2022-11-14 18:23 UTC, kingzez commented on packages/core/src/parsers/jsx/function-parser.ts
> +          [i.key?.name]: processDefaultPropsValue(i.value),
I tried, but change to `parseStateObjectToMitosisState `, the snapshot mismatched,  property `code` has extra double quote and function with name

```js
 FAIL  src/__tests__/parse-jsx.test.ts > Parse JSX > defaultProps
AssertionError: Snapshot `Parse JSX > defaultProps 1` mismatched
  - Expected  - 4
  + Received  + 4

        set": {},
      },
      "defaultProps": {
        "link": {
  -       "code": "https://builder.io/",
  +       "code": "'https://builder.io/'",
          "type": "property",
        },
        "onClick": {
  -       "code": "() => {
  +       "code": "onClick() {
      console.log('hi');
    }",
          "type": "method",
        },
        "openLinkInNewTab": {
  -       "code": false,
  +       "code": "false",
          "type": "property",
        },
        "text": {
  -       "code": "default text",
  +       "code": "'default text'",
          "type": "property",
        },
      },
      "exports": {},


```

2022-11-14 19:14 UTC, samijaber commented on packages/core/src/parsers/jsx/function-parser.ts
> +          [i.key?.name]: processDefaultPropsValue(i.value),
Oh, right! Sorry for the confusion. We recently changed this part of our JSON schema, during the time you made your PR. 

We actually no longer need to `JSON.stringify` the output in the generators! So everything that you do this:

```ts
return `${prop}: ${isMethod ? `${value}` : json5.stringify(value)}`;
```

You can now replace with just:

```ts
return `${prop}: ${value}`;
```

the `parse-jsx` snapshot are going to need to be updated, but the final code snapshots in React/Vue/etc. will remain the same.

Sorry for sending you on a long journey with this PR: I forgot to tell you all this information at the very start. Thank you for your patience 🙏🏽

2022-11-15 02:27 UTC, kingzez commented on packages/core/src/parsers/jsx/function-parser.ts
> +          [i.key?.name]: processDefaultPropsValue(i.value),
Double quotes can solve it, but function code get `onClick() {
      console.log('hi');
    }`,  the defaultProps's function should not has function name, it should be `() => {
      console.log('hi');
    }`, should not converted

Is defaultProps that should handled as state? 🤔

2022-11-15 03:22 UTC, kingzez commented on packages/core/src/parsers/jsx/function-parser.ts
> +          [i.key?.name]: processDefaultPropsValue(i.value),
https://github.com/BuilderIO/mitosis/blob/main/packages/core/src/parsers/jsx/state.ts#L108-L124

```ts
if (types.isFunctionExpression(item.value)) {
  return {
    code: parseCode(item.value),
    type: 'function',
  };
} else if (types.isArrowFunctionExpression(item.value)) {
  const n = babel.types.objectMethod(
    'method',
    item.key as babel.types.Expression,
    item.value.params,
    item.value.body as babel.types.BlockStatement,
  );
  const code = parseCode(n);
  return {
    code: code,
    type: 'method',
  };
}
```

I see this part is dealing with that PR https://github.com/BuilderIO/mitosis/pull/875

2022-11-29 14:49 UTC, samijaber approved these changes
Amazing @kingzez , thank you for this PR 😄

2022-11-29 14:49 UTC, merged